import { Item } from './index'

export const oresItems: Record<string, Item> = {
  // Common Ores
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    tier: 'common',
    category: 'ores',
    description: 'Common iron ore used for basic crafting.',
    value: 15,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Copper Ore',
    tier: 'common',
    category: 'ores',
    description: 'Versatile copper ore for various applications.',
    value: 12,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // Uncommon Ores
  silver_ore: {
    id: 'silver_ore',
    name: 'Silver Ore',
    tier: 'uncommon',
    category: 'ores',
    description: 'Shiny silver ore with good conductive properties.',
    value: 25,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Gold Ore',
    tier: 'uncommon',
    category: 'ores',
    description: 'Precious gold ore, highly valued.',
    value: 35,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // Rare Ores
  platinum_ore: {
    id: 'platinum_ore',
    name: 'Platinum Ore',
    tier: 'rare',
    category: 'ores',
    description: 'Rare platinum ore, resistant to corrosion.',
    value: 80,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  titanium_ore: {
    id: 'titanium_ore',
    name: 'Titanium Ore',
    tier: 'rare',
    category: 'ores',
    description: 'Strong and lightweight titanium ore.',
    value: 90,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // Epic Ores
  adamantium_ore: {
    id: 'adamantium_ore',
    name: 'Adamantium Ore',
    tier: 'epic',
    category: 'ores',
    description: 'Incredibly tough adamantium ore from legends.',
    value: 200,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  mithril_ore: {
    id: 'mithril_ore',
    name: 'Mithril Ore',
    tier: 'epic',
    category: 'ores',
    description: 'Mythical mithril ore, lighter than air.',
    value: 220,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // Legendary Ores
  dragon_scale_ore: {
    id: 'dragon_scale_ore',
    name: 'Dragon Scale Ore',
    tier: 'legendary',
    category: 'ores',
    description: 'Ore resembling dragon scales, incredibly durable.',
    value: 500,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  phoenix_feather_ore: {
    id: 'phoenix_feather_ore',
    name: 'Phoenix Feather Ore',
    tier: 'legendary',
    category: 'ores',
    description: 'Ore that shimmers like phoenix feathers.',
    value: 550,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // Mythical Ores
  void_crystal_ore: {
    id: 'void_crystal_ore',
    name: 'Void Crystal Ore',
    tier: 'mythical',
    category: 'ores',
    description: 'Crystal ore that absorbs light into nothingness.',
    value: 1200,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  starlight_ore: {
    id: 'starlight_ore',
    name: 'Starlight Ore',
    tier: 'mythical',
    category: 'ores',
    description: 'Ore that glows with captured starlight.',
    value: 1300,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },

  // WDYFT Ores
  quantum_ore: {
    id: 'quantum_ore',
    name: 'Quantum Ore',
    tier: 'wdyft',
    category: 'ores',
    description: 'Ore that exists in multiple states simultaneously.',
    value: 3000,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
  reality_stone_ore: {
    id: 'reality_stone_ore',
    name: 'Reality Stone Ore',
    tier: 'wdyft',
    category: 'ores',
    description: 'Ore containing the essence of reality itself.',
    value: 3500,
    usable: false,
    source: 'Found',
    breakChance: 0,
  },
}
