#!/bin/bash

# What is Life - Windows Build Script
# Cross-compiles for Windows on Linux using Tauri and cross-compilation tools

set -e

echo "🪟 What is Life - Windows Build Script"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Prerequisites Check${NC}"
echo "======================"

# Check if we're on Linux
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    echo -e "${RED}❌ This script is designed for Linux cross-compilation to Windows${NC}"
    echo "For native Windows builds, use a Windows machine with Visual Studio Build Tools"
    exit 1
fi

# Check for required tools
echo "🔍 Checking build tools..."

# Rust cross-compilation target
if ! rustup target list | grep -q "x86_64-pc-windows-msvc"; then
    echo -e "${YELLOW}⚠️ Adding Windows cross-compilation target...${NC}"
    rustup target add x86_64-pc-windows-msvc
fi

# Check for NSIS (for MSI installer)
if ! command -v makensis &> /dev/null; then
    echo -e "${YELLOW}⚠️ Installing NSIS for MSI creation...${NC}"
    sudo apt update
    sudo apt install -y nsis
fi

echo -e "${GREEN}✅ Build environment ready!${NC}"
echo ""

# Build web assets
echo -e "${BLUE}🏗️ Building web assets...${NC}"
npm run build

# Build Tauri app for Windows
echo -e "${BLUE}🪟 Building Windows executable...${NC}"
echo "This may take several minutes..."

npx tauri build --target x86_64-pc-windows-msvc

echo -e "${GREEN}✅ Windows build completed!${NC}"
echo ""

# Check if build was successful
TARGET_DIR="src-tauri/target/x86_64-pc-windows-msvc/release"

if [ -f "$TARGET_DIR/what-is-life.exe" ]; then
    echo -e "${GREEN}✅ Windows executable created successfully!${NC}"
    echo "📍 Location: $TARGET_DIR/what-is-life.exe"
    echo "📦 Size: $(du -h "$TARGET_DIR/what-is-life.exe" | cut -f1)"
    echo ""
else
    echo -e "${RED}❌ Windows build failed - executable not found${NC}"
    exit 1
fi

# Create MSI installer (optional)
echo -e "${BLUE}📦 Creating MSI installer...${NC}"

# Create NSIS script for MSI
cat > windows_installer.nsi << 'EOF'
; What is Life - Windows Installer
; Generated by build script

!include "MUI2.nsh"

Name "What is Life"
OutFile "What_Is_Life_Setup.msi"
Unicode True
InstallDir "$PROGRAMFILES\What is Life"
InstallDirRegKey HKCU "Software\What is Life" ""

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"

  ; Copy executable
  File "what-is-life.exe"

  ; Create start menu shortcut
  CreateDirectory "$SMPROGRAMS\What is Life"
  CreateShortCut "$SMPROGRAMS\What is Life\What is Life.lnk" "$INSTDIR\what-is-life.exe"
  CreateShortCut "$DESKTOP\What is Life.lnk" "$INSTDIR\what-is-life.exe"

  ; Store installation folder
  WriteRegStr HKCU "Software\What is Life" "" $INSTDIR

  ; Create uninstaller
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayName" "What is Life"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayVersion" "0.1.0"

SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\what-is-life.exe"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"
  Delete "$SMPROGRAMS\What is Life\What is Life.lnk"
  Delete "$DESKTOP\What is Life.lnk"
  RMDir "$SMPROGRAMS\What is Life"
  DeleteRegKey HKCU "Software\What is Life"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life"
SectionEnd
EOF

# Copy executable to current directory for installer
cp "$TARGET_DIR/what-is-life.exe" .

# Build MSI
if command -v makensis &> /dev/null; then
    echo "📦 Building MSI installer..."
    makensis windows_installer.nsi

    if [ -f "What_Is_Life_Setup.msi" ]; then
        echo -e "${GREEN}✅ MSI installer created: What_Is_Life_Setup.msi${NC}"
        echo "📦 Size: $(du -h "What_Is_Life_Setup.msi" | cut -f1)"
    else
        echo -e "${YELLOW}⚠️ MSI creation failed, but executable is ready${NC}"
    fi
else
    echo -e "${YELLOW}⚠️ NSIS not available - MSI not created${NC}"
    echo "💡 You can manually create an installer using the executable"
fi

# Cleanup
rm -f windows_installer.nsi what-is-life.exe

echo ""
echo -e "${GREEN}🎉 Windows build process completed!${NC}"
echo ""
echo "📋 Output Summary:"
echo "=================="
echo "• Windows executable: $TARGET_DIR/what-is-life.exe"
if [ -f "What_Is_Life_Setup.msi" ]; then
    echo "• MSI installer: What_Is_Life_Setup.msi"
fi
echo ""
echo "🚀 Next steps:"
echo "• Test the Windows executable on a Windows machine"
echo "• Use the bootstrapper script for immediate Windows compatibility"
echo "• Upload to GitHub releases for distribution"
echo ""
echo "💡 For native Windows development, use Visual Studio Build Tools on Windows"
