name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        shell: pwsh
        run: |
          $env:ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
          npm ci
          Push-Location web
          npm ci
          Pop-Location

      - name: Build web assets
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri:build:windows:msi

      - name: Create MSI installer
        run: |
          # Download and install NSIS
          choco install nsis -y

          # Create NSIS script for MSI
          cat > windows_installer.nsi << 'EOF'
          ; What is Life - Windows MSI Installer
          ; Generated by GitHub Actions

          !include "MUI2.nsh"

          Name "What is Life"
          OutFile "What_Is_Life_Setup.msi"
          Unicode True
          InstallDir "$PROGRAMFILES\What is Life"
          InstallDirRegKey HKCU "Software\What is Life" ""

          !insertmacro MUI_PAGE_WELCOME
          !insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_PAGE_FINISH

          !insertmacro MUI_UNPAGE_WELCOME
          !insertmacro MUI_UNPAGE_CONFIRM
          !insertmacro MUI_UNPAGE_INSTFILES
          !insertmacro MUI_UNPAGE_FINISH

          !insertmacro MUI_LANGUAGE "English"

          Section "Install"
            SetOutPath "$INSTDIR"

            ; Copy executable
            File "what-is-life.exe"

            ; Create start menu shortcut
            CreateDirectory "$SMPROGRAMS\What is Life"
            CreateShortCut "$SMPROGRAMS\What is Life\What is Life.lnk" "$INSTDIR\what-is-life.exe"
            CreateShortCut "$DESKTOP\What is Life.lnk" "$INSTDIR\what-is-life.exe"

            ; Store installation folder
            WriteRegStr HKCU "Software\What is Life" "" $INSTDIR

            ; Create uninstaller
            WriteUninstaller "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayName" "What is Life"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "UninstallString" "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayVersion" "0.1.1"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "Publisher" "Windsurf Engineering Team"

          SectionEnd

          Section "Uninstall"
            Delete "$INSTDIR\what-is-life.exe"
            Delete "$INSTDIR\Uninstall.exe"
            RMDir "$INSTDIR"
            Delete "$SMPROGRAMS\What is Life\What is Life.lnk"
            Delete "$DESKTOP\What is Life.lnk"
            RMDir "$SMPROGRAMS\What is Life"
            DeleteRegKey HKCU "Software\What is Life"
            DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life"
          SectionEnd
          EOF

          # Copy executable and create MSI
          cp "src-tauri/target/x86_64-pc-windows-msvc/release/what-is-life.exe" .
          makensis windows_installer.nsi

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer
          path: What_Is_Life_Setup.msi
          if-no-files-found: error

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Android APKs with Docker
        run: |
          # Build Docker image and run Android builds
          docker build -f Dockerfile.android -t android-builder .

          # Build ARM64 APK
          docker run --rm -v $(pwd):/app android-builder bash -c "
            cd /app/web/android && \
            ./gradlew assembleDebug -PabiFilter=arm64-v8a && \
            cp app/build/outputs/apk/debug/app-arm64-v8a-debug.apk /app/
          "

          # Build ARM32 APK
          docker run --rm -v $(pwd):/app android-builder bash -c "
            cd /app/web/android && \
            ./gradlew assembleDebug -PabiFilter=armeabi-v7a && \
            cp app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk /app/
          "

      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64
          path: app-arm64-v8a-debug.apk
          if-no-files-found: error

      - name: Upload ARM32 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-arm32
          path: app-armeabi-v7a-debug.apk
          if-no-files-found: error

  release:
    needs: [build-windows-msi, build-android]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release archives
        run: |
          cd artifacts
          for dir in */; do
            if [ -d "$dir" ]; then
              dirname=$(basename "$dir")
              tar -czf "${dirname}.tar.gz" -C "$dir" .
            fi
          done

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.apk
            artifacts/**/*.msi
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
