name: Build and Release Windows MSI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable

jobs:
  build-windows-msi:
    name: Build Windows MSI Installer (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dependencies
        shell: pwsh
        run: |
          $env:ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
          npm ci
          Push-Location web
          npm ci
          Pop-Location

      - name: Build web assets
        run: npm run build

      - name: Build Tauri app for Windows x64
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri:build
          args: --target x86_64-pc-windows-msvc

      - name: Install NSIS for MSI creation
        run: |
          choco install nsis -y

      - name: Create Windows MSI installer
        shell: pwsh
        run: |
          # Create NSIS script for MSI installer
          $nsisScript = @"
          ; What is Life - Windows MSI Installer
          ; Generated by GitHub Actions for x64 architecture only

          !include "MUI2.nsh"

          Name "What is Life"
          OutFile "What_Is_Life_Setup.msi"
          Unicode True
          InstallDir "$PROGRAMFILES64\What is Life"
          InstallDirRegKey HKCU "Software\What is Life" ""

          !insertmacro MUI_PAGE_WELCOME
          !insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_PAGE_FINISH

          !insertmacro MUI_UNPAGE_WELCOME
          !insertmacro MUI_UNPAGE_CONFIRM
          !insertmacro MUI_UNPAGE_INSTFILES
          !insertmacro MUI_UNPAGE_FINISH

          !insertmacro MUI_LANGUAGE "English"

          Section "Install"
            SetOutPath "$INSTDIR"

            ; Copy executable (x64 only)
            File "src-tauri\target\x86_64-pc-windows-msvc\release\what-is-life.exe"

            ; Copy additional files if they exist
            File /r "src-tauri\target\x86_64-pc-windows-msvc\release\*.*"

            ; Create start menu shortcuts
            CreateDirectory "$SMPROGRAMS\What is Life"
            CreateShortCut "$SMPROGRAMS\What is Life\What is Life.lnk" "$INSTDIR\what-is-life.exe"
            CreateShortCut "$DESKTOP\What is Life.lnk" "$INSTDIR\what-is-life.exe"

            ; Store installation folder
            WriteRegStr HKCU "Software\What is Life" "" $INSTDIR

            ; Create uninstaller
            WriteUninstaller "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayName" "What is Life"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "UninstallString" "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayVersion" "0.1.1"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "Publisher" "Windsurf Engineering Team"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "InstallLocation" "$INSTDIR"

          SectionEnd

          Section "Uninstall"
            Delete "$INSTDIR\what-is-life.exe"
            Delete "$INSTDIR\Uninstall.exe"
            RMDir /r "$INSTDIR"
            Delete "$SMPROGRAMS\What is Life\What is Life.lnk"
            Delete "$DESKTOP\What is Life.lnk"
            RMDir "$SMPROGRAMS\What is Life"
            DeleteRegKey HKCU "Software\What is Life"
            DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life"
          SectionEnd
          "@

          # Write NSIS script to file
          $nsisScript | Out-File -FilePath "windows_installer.nsi" -Encoding UTF8

          # Copy the built executable
          Copy-Item "src-tauri\target\x86_64-pc-windows-msvc\release\what-is-life.exe" .

          # Create the MSI installer
          & "C:\Program Files (x86)\NSIS\makensis.exe" windows_installer.nsi

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer-x64
          path: What_Is_Life_Setup.msi
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: [build-windows-msi]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Download MSI installer
        uses: actions/download-artifact@v4
        with:
          name: windows-msi-installer-x64
          path: artifacts

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/What_Is_Life_Setup.msi
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
