name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, i686-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install cross-compilation tools
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu gcc-i686-linux-gnu

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri:build -- --target ${{ matrix.target }}
          includeRelease: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri:build -- --target x86_64-pc-windows-msvc
          includeRelease: true

      - name: Create MSI installer
        run: |
          # Download and install NSIS
          choco install nsis -y

          # Create NSIS script
          cat > windows_installer.nsi << 'EOF'
          ; What is Life - Windows Installer
          ; Generated by GitHub Actions

          !include "MUI2.nsh"

          Name "What is Life"
          OutFile "What_Is_Life_Setup.msi"
          Unicode True
          InstallDir "$PROGRAMFILES\What is Life"
          InstallDirRegKey HKCU "Software\What is Life" ""

          !insertmacro MUI_PAGE_WELCOME
          !insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
          !insertmacro MUI_PAGE_DIRECTORY
          !insertmacro MUI_PAGE_INSTFILES
          !insertmacro MUI_PAGE_FINISH

          !insertmacro MUI_UNPAGE_WELCOME
          !insertmacro MUI_UNPAGE_CONFIRM
          !insertmacro MUI_UNPAGE_INSTFILES
          !insertmacro MUI_UNPAGE_FINISH

          !insertmacro MUI_LANGUAGE "English"

          Section "Install"
            SetOutPath "$INSTDIR"

            ; Copy executable
            File "what-is-life.exe"

            ; Create start menu shortcut
            CreateDirectory "$SMPROGRAMS\What is Life"
            CreateShortCut "$SMPROGRAMS\What is Life\What is Life.lnk" "$INSTDIR\what-is-life.exe"
            CreateShortCut "$DESKTOP\What is Life.lnk" "$INSTDIR\what-is-life.exe"

            ; Store installation folder
            WriteRegStr HKCU "Software\What is Life" "" $INSTDIR

            ; Create uninstaller
            WriteUninstaller "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayName" "What is Life"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "UninstallString" "$INSTDIR\Uninstall.exe"
            WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life" "DisplayVersion" "0.1.0"

          SectionEnd

          Section "Uninstall"
            Delete "$INSTDIR\what-is-life.exe"
            Delete "$INSTDIR\Uninstall.exe"
            RMDir "$INSTDIR"
            Delete "$SMPROGRAMS\What is Life\What is Life.lnk"
            Delete "$DESKTOP\What is Life.lnk"
            RMDir "$SMPROGRAMS\What is Life"
            DeleteRegKey HKCU "Software\What is Life"
            DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\What is Life"
          SectionEnd
          EOF

          # Copy executable and create MSI
          cp "src-tauri/target/x86_64-pc-windows-msvc/release/what-is-life.exe" .
          makensis windows_installer.nsi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: |
            What_Is_Life_Setup.msi
            src-tauri/target/x86_64-pc-windows-msvc/release/what-is-life.exe
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri:build:macos
          includeRelease: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64
          path: |
            src-tauri/target/x86_64-apple-darwin/release/bundle/**/*
          if-no-files-found: error

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64, armeabi-v7a, x86]
        abi_name: [arm64, x86_64, arm32, x86]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: android
          abi: ${{ matrix.abi }}

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build

      - name: Setup Capacitor Android
        run: |
          cd web
          npm install @capacitor/android
          npx cap add android
          npx cap sync android

      - name: Build Android APK
        run: |
          cd web/android
          ./gradlew assembleDebug -PabiFilter=${{ matrix.abi }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.abi_name }}
          path: |
            web/android/app/build/outputs/apk/debug/app-${{ matrix.abi }}-debug.apk
          if-no-files-found: error

  release:
    needs: [build-linux, build-windows, build-macos, build-android]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release archives
        run: |
          cd artifacts
          for dir in */; do
            if [ -d "$dir" ]; then
              dirname=$(basename "$dir")
              tar -czf "${dirname}.tar.gz" -C "$dir" .
            fi
          done

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.AppImage
            artifacts/**/*.msi
            artifacts/**/*.dmg
            artifacts/**/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
